apiVersion: apps/v1
kind: Deployment
metadata:
  name: mbooks
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mbooks
  template:
    metadata:
      labels:
        app: mbooks
    spec:
      terminationGracePeriodSeconds: 0
      containers:
      - name: mbooks
        image: libsgh/MBooks:java-maven
        imagePullPolicy: Always
        ports:
        - containerPort: 8080

---

apiVersion: v1
kind: Service
metadata:
  name: mbooks
  annotations:
    dev.okteto.com/auto-ingress: "true"
  labels:
    app: mbooks
spec:
  type: ClusterIP
  ports:
    - name: mbooks
      port: 8080
  selector:
    app: mbooks
